plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cdevworks.filescryptpro'
    compileSdk 33

    defaultConfig {
        applicationId "com.cdevworks.filescryptpro"
        minSdk 26
        targetSdk 33
        versionCode 27
        versionName '3.3'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_9
        targetCompatibility JavaVersion.VERSION_1_9
    }
}

dependencies {
    def billing_version = "6.0.1"
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'androidx.core:core-splashscreen:1.0.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "androidx.biometric:biometric:1.1.0"
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.google.android.gms:play-services-ads:22.3.0'
    implementation 'com.google.android.play:integrity:1.2.0'
    implementation 'com.google.android.play:app-update:2.1.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation "com.android.billingclient:billing:$billing_version"
    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
    implementation 'com.google.guava:guava:24.1-jre'
}